### ISSUE TITLE
Escher Chem Synth

### ISSUE THREAD

**Issue by slartibartfastMC** [pinecones/Necromunda_Underhive#2]
From what I can see no Escher models can take a Chem-Synth from the Escher wargear as listed in the Escher equipment for 10 credits.

**Comment by pinecones** [comment]
Doh! It has been added but not assigned to wargear. I will update and recompile when I get home. Tomorrow I should be able to squeeze it in. Thanks for identifying it!

**Comment by slartibartfastMC** [comment]
I don't think Escher can take the Stimm-Slug Stash either but it is listed as available to take.

**Comment by pinecones** [comment]
Ohhhh. You are right. I copied the wargear group selection from Goliath and added the extra ones for Escher.
Update it soon :)

**Comment by pinecones** [comment]
Afternoon,

I have updated the repo and the Escher file, not only was Stimm-slug available for Escher, but they were also missing Chem-synth as wargear. Both issues have been resolved.

Thanks for logging this issue 👍
