### ISSUE TITLE
Chem-Synth

### ISSUE THREAD

**Issue by slartibartfastMC** [pinecones/Necromunda_Underhive#3]
Thanks for the update to the wargear, although currently the Chem-Synth is listed as no cost whereas it should be 10 credits.

**Comment by pinecones** [comment]
I thought I snuck that update out. Try it again now :)

Thanks for your patience and help. I am still trying to figure out the kinks of this application and github.

I will await confirmation before closing this one.

**Comment by slartibartfastMC** [comment]
Can confirm its working

**Comment by pinecones** [comment]
Thanks for the quick response!
